[build]
  base = "exampleSite"
  command = "hugo --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.135.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.135.0"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.135.0"

# Redirect rules for better SEO
[[redirects]]
  from = "/posts/*"
  to = "/posts/:splat"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000" 