baseURL = "https://mynewhugosite.com"
title = "محمد"
theme = "zahi"
languageCode = "ar"
defaultContentLanguage = "ar"

[taxonomies]
tag = "tags"

[params]
github = "https://www.github.com/mohamedelhefni"
mail = "mailto:mohamed.elhefni@outlook.com"
site = "https://hefni101.netlify.app/"

[services]
[services.disqus]
shortname = 'foobar'

